-- Simple demo seed data (IDs are generated by DB)
INSERT INTO schools (owner_user_id, name, description, is_verified)
VALUES ('seed-owner', 'Seed Academy', 'Demo school for development', true)
ON CONFLICT DO NOTHING;

-- Link owner as admin
INSERT INTO school_members (school_id, user_id, role)
SELECT s.id, 'seed-owner', 'admin' FROM schools s WHERE s.name='Seed Academy'
ON CONFLICT DO NOTHING;

-- Tutor and Class
INSERT INTO classes (school_id, tutor_user_id, title, description, visibility, is_paid, price_cents)
SELECT s.id, 'seed-tutor', 'Algebra I', 'Introduction to Algebra', 'public', false, 0 FROM schools s WHERE s.name='Seed Academy'
ON CONFLICT DO NOTHING;

-- Subject
INSERT INTO subjects (class_id, title, description, order_index)
SELECT c.id, 'Basic Concepts', 'Numbers and operations', 1 FROM classes c WHERE c.title='Algebra I'
ON CONFLICT DO NOTHING;

-- Lessons
INSERT INTO lessons (subject_id, title, type, content, order_index, is_free)
SELECT sub.id, 'Integers 101', 'text', '{"body":"What are integers?"}', 1, true
FROM subjects sub WHERE sub.title='Basic Concepts'
ON CONFLICT DO NOTHING;

INSERT INTO lessons (subject_id, title, type, content, order_index, is_free)
SELECT sub.id, 'Number Line', 'video', '{"url":"https://example.com/video.mp4"}', 2, false
FROM subjects sub WHERE sub.title='Basic Concepts'
ON CONFLICT DO NOTHING;